---
language: ruby
rvm:
  - 2.0.0
  - ruby-head
bundler_args: -j4
env:
  - PADRINO_ENV=test
before_install:
  - gem update --system
  - gem --version
  - gem install bundler --pre
before_script:
  - bundle exec rake ci:prepare
script: bundle exec rake spec
after_script: test -f /tmp/create_new_entry.png && curl -X POST 'imagedata=@/tmp/create_new_entry.png' -F 'filename=gyazo.com' gyazo.com/upload.cgi
matrix:
  allow_failures:
    - rvm: ruby-head
