---
language: ruby
rvm:
  - 2.0.0
  - ruby-head
bundler_args: -j4
env:
  - PADRINO_ENV=test
before_install:
  - gem update --system
  - gem --version
  - gem install bundler --pre
before_script:
  - bundle exec rake db:create db:migrate
script: bundle exec rake spec
matrix:
  allow_failures:
    - rvm: ruby-head
