---
language: ruby
rvm:
  - 2.0.0
  - ruby-head
services:
  - redis-server
bundler_args: -j4
env:
  - PADRINO_ENV=test
before_install:
  - gem update --system
  - gem --version
  - gem install bundler --pre
before_script:
  - bundle exec rake ci:prepare
script: bundle exec rake coverage
matrix:
  allow_failures:
    - rvm: ruby-head
