---
default: &default
  :site_title: 青き花へ
  :title_placeholder: ✖
  :body_placeholder: 川は洗濯、山は芝刈りです

:development:
  <<: *default
  :host: deary.dev

:test:
  <<: *default
  :host: localhost

:production:
  <<: *default
  :host: diary.aereal.org
